packages:
  - "apps/*"
  - "packages/*"

catalog:
  react: 18.3.1
  react-dom: 18.3.1
  "@types/react": 18.3.3
  "@types/react-dom": 18.3.1
  tsup: 8.2.4
  typescript: 5.2.2
  zod: 3.25.50
  "@react-email/components": 0.0.22
